### ISSUE TITLE
Epilipid identification errors

### ISSUE THREAD

**Issue by nreimers99** [LMAI-TUD/lpptiger2#1]
Hello,

I am a lipids researcher at UW and am trying to use LPPTiger2 to identify epilipids in my LC-IM-MSe data. I input a .mzml file and refined .json list and it returned a blank .xlsx file, an empty images folder, and said "sorry there was an error". What could cause this to happen?

Thank you!

**Comment by ZhixuNi** [comment]
Hi! Many thanks for the feedback. we do NOT yet support IM-MSe data. For accuracy issues, I would recommend you to run normal DDA and try again. Thanks!
